function VehicleFixes()
	setModelHandling(400, "mass", 2500)
	setModelHandling(400, "turnMass", 5700)
	setModelHandling(400, "dragCoeff", 2.5)
	setModelHandling(400, "centerOfMass", {0.0, 0.0, -0.3} )
	setModelHandling(400, "percentSubmerged", 80)
	setModelHandling(400, "tractionMultiplier", 0.65)
	setModelHandling(400, "tractionLoss", 0.89)
	setModelHandling(400, "tractionBias", 0.5)
	setModelHandling(400, "numberOfGears", 5)
	setModelHandling(400, "maxVelocity", 160)
	setModelHandling(400, "engineAcceleration", 10)
	setModelHandling(400, "engineInertia", 25)
	setModelHandling(400, "driveType", "awd")
	setModelHandling(400, "engineType", "petrol")
	setModelHandling(400, "brakeDeceleration", 7)
	setModelHandling(400, "brakeBias", 0.45)
	setModelHandling(400, "ABS", false)
	setModelHandling(400, "steeringLock", 35)
	setModelHandling(400, "suspensionForceLevel", 1)
	setModelHandling(400, "suspensionDamping", 0.05)
	setModelHandling(400, "suspensionHighSpeedDamping", 0.0)
	setModelHandling(400, "suspensionUpperLimit", 0.40)
	setModelHandling(400, "suspensionLowerLimit", -0.2)
	setModelHandling(400, "suspensionFrontRearBias", 0.5)
	setModelHandling(400, "suspensionAntiDiveMultiplier", 0.3)
	setModelHandling(400, "seatOffsetDistance", 0.44)
	setModelHandling(400, "collisionDamageMultiplier", 0.35)
	setModelHandling(400, "modelFlags", 0x20)
	setModelHandling(400, "handlingFlags", 0x304407)
	setModelHandling(400, "headLight", 1)
	setModelHandling(400, "tailLight", 1)
	setModelHandling(400, "animGroup", 0)	
    
	setModelHandling(546, "mass", 1600)
	setModelHandling(546, "turnMass", 4500)
	setModelHandling(546, "dragCoeff", 2)
	setModelHandling(546, "centerOfMass", {0.0, 0.3, -0.1} )
	setModelHandling(546, "percentSubmerged", 75)
	setModelHandling(546, "tractionMultiplier", 0.75)
	setModelHandling(546, "tractionLoss", 0.85)
	setModelHandling(546, "tractionBias", 0.52)
	setModelHandling(546, "numberOfGears", 5)
	setModelHandling(546, "maxVelocity", 200)
	setModelHandling(546, "engineAcceleration", 10)
	setModelHandling(546, "engineInertia", 10)
	setModelHandling(546, "driveType", "rwd")
	setModelHandling(546, "engineType", "petrol")
	setModelHandling(546, "brakeDeceleration", 10)
	setModelHandling(546, "brakeBias", 0.53)
	setModelHandling(546, "ABS", false)
	setModelHandling(546, "steeringLock", 35)
	setModelHandling(546, "suspensionForceLevel", 0.9)
	setModelHandling(546, "suspensionDamping", 0.08)
	setModelHandling(546, "suspensionHighSpeedDamping", 0.0)
	setModelHandling(546, "suspensionUpperLimit", 0.28)
	setModelHandling(546, "suspensionLowerLimit", -0.17)
	setModelHandling(546, "suspensionFrontRearBias", 0.55)
	setModelHandling(546, "suspensionAntiDiveMultiplier", 0.0)
	setModelHandling(546, "seatOffsetDistance", 0.2)
	setModelHandling(546, "collisionDamageMultiplier", 0.24)
	setModelHandling(546, "modelFlags", 0x40000000)
	setModelHandling(546, "handlingFlags", 0x10200008)
	setModelHandling(546, "headLight", 1)
	setModelHandling(546, "tailLight", 3)
	setModelHandling(546, "animGroup", 0)
	
	-- Maxime 30/3/2013 :Change Yosemite handling.
	local handlingDescription = {"mass", "turnMass", "dragCoeff", "centerOfMass", "percentSubmerged", "tractionMultiplier", "tractionLoss", "tractionBias", "engineAcceleration", "driveType", "engineType", "brakeBias", "ABS", "steeringLock", "suspensionForceLevel", "suspensionDamping", "suspensionHighSpeedDamping", "suspensionUpperLimit", "suspensionLowerLimit", "suspensionFrontRearBias", "suspensionAntiDiveMultiplier"}
    for i,v in ipairs(handlingDescription) do
		local handlingVehicle = getOriginalHandling(getVehicleModelFromName("FBI Rancher"))
		setModelHandling(554, v, handlingVehicle[v])
    end
    setModelHandling(554, "maxVelocity", 140)
    setModelHandling(554, "engineAcceleration", 10)
end
--addEventHandler("onResourceStart", resourceRoot, VehicleFixes) --Disabled by MAXIME
			