txd = engineLoadTXD ( "riot_shield.txd" )
engineImportTXD ( txd, 1631)
dff = engineLoadDFF ( "riot_shield.dff", 1631 )
col = engineLoadCOL("riot_shield.col")
engineReplaceCOL(col, 1631)
engineReplaceModel(dff, 1631)

txds = engineLoadTXD ( "light.txd" )
engineImportTXD ( txds, 3895)
dffs = engineLoadDFF ( "light.dff", 3895 )
cols = engineLoadCOL("PoliceLight1.col")
engineReplaceCOL(cols, 3895)
engineReplaceModel(dffs, 3895)

addEventHandler( "onClientResourceStart", resourceRoot,
    function()

        as = dxCreateTexture ( "pd.png" )
        asshader = dxCreateShader( "as.fx" )
        engineApplyShaderToWorldTexture ( asshader, "vehiclepoldecals128" )
		engineApplyShaderToWorldTexture ( asshader, "ambulan92decal128" )
		engineApplyShaderToWorldTexture ( asshader, "securica92decal128" )
		engineApplyShaderToWorldTexture ( asshader, "topfun92decals128" )
		engineApplyShaderToWorldTexture ( asshader, "topfun92decals128a" )
		engineApplyShaderToWorldTexture ( asshader, "cement92logo" )
		engineApplyShaderToWorldTexture ( asshader, "trash92decal128" )
		engineApplyShaderToWorldTexture ( asshader, "sweeper92decal128" )
		engineApplyShaderToWorldTexture ( asshader, "polmav92sadecal64" )
		engineApplyShaderToWorldTexture ( asshader, "sd1" )
		engineApplyShaderToWorldTexture ( asshader, "sd2" )
		engineApplyShaderToWorldTexture ( asshader, "SheriFFbadges" )
		engineApplyShaderToWorldTexture ( asshader, "bus92decals128" )
		engineApplyShaderToWorldTexture ( asshader, "hotdog92signs256" )
        dxSetShaderValue ( asshader, "asTexture", as )   
    end
    )